config/routes.rb
Rails.application.routes.draw do

  root 'schools#root'
  get 'faq' => 'administrators#faq'
  get 'links' => 'administrators#links'
  get 'contact' => 'administrators#contact'

  get 'schools/search' => 'schools#search'

  resources :schools do
    resources :courses
    resources :comments, only: [:create, :destroy]
    resources :homestays
  end

  resources :maestros do
  end

  resources :administrators do
  end

  get 'sessions/new' => 'sessions#new', as: 'log-in'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy', as: 'log-out'

end

app/models/school.rb
class School < ActiveRecord::Base

  has_many :courses
  has_many :homestays
  has_many :comments

  accepts_nested_attributes_for :courses, allow_destroy: true
  accepts_nested_attributes_for :homestays, allow_destroy: true
  accepts_nested_attributes_for :comments

  def self.search(col, search=nil)
    if search
      self.where("#{col} LIKE?", "%#{search}%")
    else
      self.all
    end
  end

  # def cost
  #   (self.course.price)+(self.homestay_price)
  # end





  # def get_image

  #   if self.image_url.nil?
  #     # ALL THE CODE TO GET AN IMAGE
  #   end

  #   self.image_url

  # end




end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

#Maestros should only be able to edit a school when maestro[school_id] = school_id
  # before_action :authorize, only: [:edit]


  def root
    @schools_path = '/schools'
  end

  def index
    @schools = School.all
  end


  def new
    @school = School.new
    @school.courses.build
  end

  def create
    new_school = School.create(school_params)

    new_course = Course.create(course_params)
    new_school.courses << new_course

    redirect_to schools_path
  end

  def show
    @school = School.find(params[:id])
    @photo_urls = FlickrHelper.flickr_photos(@school).sample(3)
    @photo_url = FlickrHelper.flickr_photos(@school).first
    @photo_url2 = FlickrHelper.flickr_photos(@school).last
    @comment = Comment.new
    # new_comment = Comment.create(comment_params)
    # @school.comments << new_comment
  end


  def edit
    @school = School.find(params[:id])
    # if @school.maestro_id != current_user.id
    #   redirect_to root_path
    # end
  end

  def update
    upd_school = School.find(params[:id])
    upd_school.update(school_params)

    new_course = Course.create(course_params)
    upd_school.courses << new_course

    redirect_to school_path(upd_school)
  end

  def destroy
    School.delete(params[:id])
    Course.delete(params[:id])

    redirect_to schools_path
  end


  def search
     @schools = School.search(params[:col], params[:search])
     render 'index'
  end



  private

  def school_params
    params.require(:school).permit(:name, :website, :city, :address, :founded_by, :year_founded, :accreditation, :num_teachers, :av_years_experience, :teacher_pay, :num_tot_students, :openings, :summary, :methods, :materials, :soc_activities, :volunteering_op, :soc_initiatives, :host_families, :get_there, :more_info, :touristy, :mayan_lang, :childrens_prog, :teens_prog, :seniors_prog, :professional_prog, :prof_prog_descrip, :sp_teachers_prog, :distance_edu, :distance_descrip, :test_prep, :other_prog, :describe, :disability_accesib, :airport_pickup, :img1, :img2, :img3, :img4, :img5, :courses_attributes, :admin_fee, :max_students_per_class, :per_hr_private, :per_hr_group, :course, :comment, :homestay, :homestay_price, :meals_incl, :meals_add_price)
  end

  def course_params
    params[:school][:course].permit(:hrs_per_wk, :price_change, :description, :homestay_incl, :price, :name)
  end

  # def comment_params
  #   params[:school][:comments].permit(:user_name, :email, :source, :message)
  # end

end

app/views/schools/_form_basic.html.erb
<%= form_for @school do |f| %>
  <h3>BASIC INFO</h3>
  Name: <%= f.text_field          :name %> <br />
  Website: <%= f.text_field       :website %> <br />
  City: <%= f.text_field          :city %> <br />
  Address: <%= f.text_field       :address %> <br />
  Email: <%= f.text_field         :email %> <br />
  Phone: <%= f.text_field         :phone %> <br />

  <h3>FULLER DESCRIPTIONS</h3>
  Summary: <%= f.text_area        :summary %> <br />

  <h3>TOP PHOTOS</h3>
  ImageURL: <%= f.text_field      :img3 %> <br />
  ImageURL: <%= f.text_field      :img4 %> <br />
  ImageURL: <%= f.text_field      :img5 %> <br />

  <h3>COURSE INFORMATION</h3>
  Administrative Fee: <%= f.text_field :admin_fee %><br />
  Price per Hour Private Lessons: <%= f.text_field :per_hr_private %><br />
  Price per Hour Group Lessons: <%= f.text_field :per_hr_group %><br />
  Maximum Students per Class: <%= f.text_field :max_students_per_class %><br />

  <h3>WHAT IS YOUR MOST POPULAR CLASS?</h3>
  <%= f.fields_for :course do |cf| %>
    Name of class: <%= cf.text_field :name %><br />
    Describe the class: <%= cf.text_area :description %><br />
    Hours per Week: <%= cf.text_field :hrs_per_wk %><br />
    Price per Week: <%= cf.text_field :price %><br />
    Homestay included: <%= cf.text_field :homestay_incl %><br />
    Price change over time: <%= cf.text_area :price_change %><br />
  <% end %>

  <h3>WHAT IS YOUR MOST POPULAR HOMESTAY OPTION?</h3>
  Describe: <%= f.text_field       :homestay %><br />
  Price/wk in USD: <%= f.text_field :homestay_price %><br />
  Check if Meals are included: <%= f.check_box :meals_incl %><br />
  If not, how much additional cost USD per meal: <%= f.text_field :meals_add_price %><br />

  <%= f.submit %>
<% end %>

app/views/schools/_form_courses.html.erb
<%= form_for @school do |f| %>
  <%= f.fields_for :course do |cf| %>
    Name of class: <%= cf.text_field :name %><br />
    Describe the class: <%= cf.text_area :description %><br />
    Hours per Week: <%= cf.text_field :hrs_per_wk %><br />
    Price per Week: <%= cf.text_field :price %><br />
    Homestay included: <%= cf.text_field :homestay_incl %><br />
    Price change over time: <%= cf.text_area :price_change %><br />
  <% end %>
<% end %>

app/views/schools/_rating_widget.html.erb
<script type="text/javascript">(function(d, t, e, m){
    // Async Rating-Widget initialization.
    window.RW_Async_Init = function(){
        RW.init({
            huid: "173546",
            uid: "726ef8fd3e8ae6ef5e42470289677e07",
            source: "website",
            options: {
                "advanced": {
                    "text": {
                        "rateThis": ""
                    }
                },
                "style": "flat_yellow"
            }
        });
        RW.render();
    };

    // Append Rating-Widget JavaScript library.
    var rw, s = d.getElementsByTagName(e)[0], id = "rw-js",
        l = d.location, ck = "Y" + t.getFullYear() +
        "M" + t.getMonth() + "D" + t.getDate(), p = l.protocol,
        f = (-1 < l.search.indexOf("DBG=") ? "" : ".min"),
        a = ("https:" == p ? "secure." + m + "js/" : "js." + m);
    if (d.getElementById(id)) return;
    rw = d.createElement(e);
    rw.id = id; rw.async = true; rw.type = "text/javascript";
    rw.src = p + "//" + a + "external" + f + ".js?ck=" + ck;
    s.parentNode.insertBefore(rw, s);
}(document, new Date(), "script", "rating-widget.com/"));</script>

app/views/schools/edit.html.erb
<h1>This is the school! </h1>

<%= render 'form_basic' %>

<a href="/schools">HOME</a>

app/views/schools/edit_courses.html.erb
<h1>Make a new course! </h1>
<%= form_for @school do |f| %>
  <%= f.fields_for :course do |cf| %>
    Name of class: <%= cf.text_field :name %><br />
    Describe the class: <%= cf.text_area :description %><br />
    Hours per Week: <%= cf.text_field :hrs_per_wk %><br />
    Price per Week: <%= cf.text_field :price %><br />
    Homestay included: <%= cf.text_field :homestay_incl %><br />
    Price change over time: <%= cf.text_area :price_change %><br />
  <% end %>
<% end %>

<a href="/schools">HOME</a>

app/views/schools/index.html.erb
<div class="top"></div>
  <div class="head">
    <div class="header">
      <button class="nav" action="<%= schools_path %>">HOME</button>
      <a href="/faq"><button class="nav">FAQ</button></a>
      <a href="/links"><button class="nav" action="<%= schools_path %>">USEFUL LINKS</button></a>
      <a href="/contact"><button class="nav" action="<%= schools_path %>">CONTACT</button></a>
    </div>

    <div class="title">
      <h1>< Spanish Immersion ></h1>
    </div>

    <div class="subdiv">
      <h4 class="sub1"> . About </h4>
      <h4 class="sub2"> . . . Search </h4>
      <h4 class="sub3"> . . . . . Listing </h4>
    </div>

    <div class="header index">
      <div class="administrative button"><a href="/schools/new">Log <br>In</a>
      </div>
    </div>

    <!--   <div class="administrative button"><a href="/schools/new">
        New School</a></div> -->

    <div class="hover-div">
      <img class="wordle" src="https://mail.google.com/mail/u/0/?ui=2&ik=a406f72f4c&view=fimg&th=14622e05c2c12117&attid=0.1&disp=inline&realattid=f_hvhr35kf1&safe=1&attbid=ANGjdJ92ZP09u4q92yHp3N3CI6WZOJoVE5na5G_0J08WVAC5hiGuRvxRJB4k1b2qxADdEjhZHy4avvMnWp9UlKneTxO8oOh2VSZcbkwYV37CqfVl5l7NKCTVJpsEXEA&ats=1400744468409&rm=14622e05c2c12117&zw&sz=w539-h773" alt="">
    </div>

    <span class="wordle-element">Make your own word map! <a href="http://www.wordle.net">Use Wordle</a></span>

    <div class="about right">
      <p>We live in an increasingly bi-lingual society. Turn your next adventure in Mexico into a true learning experience. Learn through immersion. This site aims to make your choice easier, by helping you choose the right school for you. Check out the school pages, and search through the many options!
      </p>
    </div>
  </div>

  <div class="about header">

    </div>
  <div class= "find_it about">
    <div class="search">
      <h3>Search by Name</h3>
      <form action="/schools/search" method='get'>
        <input type="hidden" name='col' value='name'>
        <input type="text" name='search'>
        <input type="submit">
      </form>


    <h3>Search by City</h3>
    <form action="/schools/search" method='get'>
      <input type="hidden" name='col' value='city'>
      <input type="text" name='search'>
      <input type="submit">
    </form>
  </div>

  <div class="map "><img src="http://maps.googleapis.com/maps/api/staticmap?center=Mexico&zoom=5&size=750x550&&maptype=satellite&sensor=true_or_false" alt=""></div>
</div>

<div class="header about"></div>

<div class ="listing about">
<h2>< THE COURSES ></h2>
  <table>
      <tr>
        <th>School </td>
        <th> City </th>
        <th> Courses </td>
      </tr>
    <% @schools.each do |school| %>
      <tr>
        <td><a href= <%= school_path(school) %> ><em><%= school.name %></em></a> <br />
          <div class="rw-ui-container rw-urid-<%= @school_id %>"></div>
        </td>
        <td><%= school.city %></td>
        <td>
          <% school.courses.each do |course| %>
          <li> <%= course.name %> ( <%= course.hrs_per_wk %>hrs/wk => $<%= course.price %> )</li>
          <% end %>
        </td>
      </tr>
    <%end %>
  </table>
</div>
<br />

<div class="header about"><div class="administrative button"><a href="/schools/new">New School</a></div></div>

<div class="administrative list about">
  <% @schools.each do |school| %>
    <ul>
      <li>
        <a href="<%= school.website %>"><%= school.name %></a>

        <form action="/schools/<%= school.id %>" method="post">
          <%= token_tag %>
          <input type="hidden" name="_method" value="delete">
          <button type="submit">DELETE</button>
        </form>

        <a href="/schools/<%= school.id %>">SHOW</a>
        <a href="/schools/<%= school.id %>/edit">EDIT</a>
      </li><br>
    </ul>
  <% end %>
</div>





<div class="me">
  Please contact me at: <br />
  kristen.tonga@gmail.com <br />
  or visit me on: <br />
</div>


<div class="bottom"></div>

<!-- THESE ARE THE STAR RATING SYSTEMS -->
<%= render 'rating_widget' %>

app/views/schools/new.html.erb
<h1>Create a new school! </h1>

<%= render 'form_basic' %>

app/views/schools/new_full.html.erb
new =>
    @school.courses.build

create =>
    params[:school][:courses_attributes].each do |key, course_params|
      new_course = Course.create(course_params)
      new_school.courses << new_course

--------------


<h1>Create a new school! </h1>

<%= form_for @school do |f| %>
   <h3>BASIC INFO</h3>
  Name: <%= f.text_field              :name %> <br />
  Website: <%= f.text_field           :website %> <br />
  City: <%= f.text_field              :city %> <br />
  Address: <%= f.text_field           :address %> <br />
  Founded By: <%= f.text_field        :founded_by %> <br />
  Founded in Year: <%= f.text_field   :year_founded %> <br />
  Accreditation: <%= f.text_area      :accreditation %> <br />

  <h3>TEACHER INFO</h3>
  Number of Teachers: <%= f.text_field                  :num_teachers %> <br />
  Average Years of Experience: <%= f.text_field         :av_years_experience %> <br />
  How much are Teachers Paid weekly in USD: <%= f.text_field :teacher_pay %> <br />
  Number of Students (total): <%= f.text_field          :num_tot_students %> <br />
  Openings/Registration: <%= f.text_area                :openings %> <br />

 <h3>FULLER DESCRIPTIONS</h3>
  Summary: <%= f.text_area                              :summary %> <br />
  Methods: <%= f.text_area                              :methods %> <br />
  Materials: <%= f.text_area                            :materials %> <br />
  Social Activities: <%= f.text_area                    :name %> <br />
  Volunteering Opportunities: <%= f.text_area           :volunteering_op %> <br />
  Social Initiatives: <%= f.text_area                   :soc_initiatives %> <br />
  Host Families: <%= f.text_area                        :host_families %> <br />
  How to Get there: <%= f.text_area                     :get_there %> <br />  Further Information: <%= f.text_area :more_info %> <br />

   <h3>CLASS INFO</h3>
   <h4>Click if you provide:</h4>
  Teach a Language other than Spanish: <%= f.check_box  :mayan_lang %> <br />
  Childrens Program: <%= f.check_box                    :childrens_prog %> <br />
  Teens Program: <%= f.check_box                        :teens_prog %> <br />
  Program for Seniors: <%= f.check_box                  :seniors_prog %> <br />
  Program for Professionals: <%= f.check_box            :professional_prog %> Which Programs: <%= f.text_field     :prof_prog_descrip %> <br />
  Spanish Teachers Program: <%= f.check_box             :sp_teachers_prog %> <br />
  Distance Program: <%= f.check_box                     :distance_edu %> How does it work: <%= f.text_field        :distance_descrip %> <br />
  Other Programs: <%= f.check_box                       :other_prog %> Which Programs: <%= f.text_field            :other_progr_descr %> <br />
  Disability Accesible Faculties: <%= f.check_box       :disability_accesib %> <br />
  Airport Pickup Available: <%= f.check_box             :airport_pickup %> <br />

 <h3>COURSE INFO</h3>
  <%= f.fields_for :courses do | course_fields | %>

      Hours per Week: <%= course_fields.number_field                    :hrs_per_wk %> <br />
      Price per Week, private:  <%= course_fields.number_field            :price_priv %> <br />
      Price per Week, group: <%= course_fields.number_field              :price_grp %> <br />
      Price change:       <%= course_fields.number_field               :price_change %> <br />
      Maximum number of students: <%= course_fields.number_field          :max_students %> <br />
      Description of course: <%= course_fields.number_field            :description %> <br />
      Homestay included: <%= course_fields.number_field                :homestay_incl %> <br />

  <% end %>

   <h3>BASIC INFO</h3>
  ImageURL: <%= f.text_field          :img1 %> <br />
  ImageURL: <%= f.text_field          :img2 %> <br />
  ImageURL: <%= f.text_field          :img3 %> <br />
  ImageURL: <%= f.text_field          :img4 %> <br />
  ImageURL: <%= f.text_field          :img5 %> <br />

  <%= f.submit %>
<% end %>

app/views/schools/root.html.erb
</div>


<div class="black">

<h1>FIND A SPANISH IMMERSION PROGRAM:</h1>
<table>
  <tr>
    <td>
      <a href="<%= schools_path %>"><div class="country mexico"><img class="root" src="http://us.123rf.com/450wm/creativedoxfoto/creativedoxfoto1110/creativedoxfoto111000031/11282881-old-grunge-flag-of-mexico.jpg" alt=""></div></a>
    </td>
    <td>
      <h1 class="root">MEXICO</h1>
    </td>
  </tr>
</table>
<br>
 <h1 class="root">>>>>>>>>>>>>>>>>>>>>>> PICK  </h1><br />
 <br>
<table>
  <tr>
    <td>
      <h1 class="root">Guatemala</h1>
    </td>
    <td>
      <a href="http://www.guatemala365.com/"><div class="country guatamala">  <img class="root" src="http://us.123rf.com/400wm/400/400/haak78/haak780910/haak78091000091/5708075-coffee-beans--guatemala.jpg" alt=""></div></a>
    </td>
  </tr>
</table>

<img src="https://mail.google.com/mail/u/0/?ui=2&ik=a406f72f4c&view=fimg&th=146239fc3a0f48c0&attid=0.1&disp=inline&realattid=f_hvhyk0ht1&safe=1&attbid=ANGjdJ8AFByv32fYIpotk7zLJbMRjsKnNEkZHe8O6zDADk_74S37gLM4cdrweWxKLKaGrggEKgrd57LVA9GS-d-eCfJkx1g4msGPQn5qj21H3Vt9NzGatvxApOF9l5k&ats=1400757011680&rm=146239fc3a0f48c0&zw&sz=w722-h773" alt="">

</div>
 <h1 class="left"> < Spanish Immersion Programs > </h1>



</div>

app/views/schools/show.html.erb
  <div class="intro">
    <div class="top">
    <div class="margin">
      <a href="/schools"><button class="nav">HOME</button></a>
      <a href="/faq"><button class="nav">FAQ</button></a>
      <a href="/links"><button class="nav" action="<%= schools_path %>">USEFUL LINKS</button></a>
      <a href="/contact"><button class="nav" action="<%= schools_path %>">CONTACT</button></a>
    </div>
<div class="rw-ui-container rw-urid-<%= @school_id %>"></div>
    </div>
    <div class="header">
    </div>

    <div class="wrapA">
      <% @photo_urls.each do |url| %>
      <img class="flickr_photo" src="<%= url %>" alt="">
      <% end %>
    </div>

    <div class="city" >
      <h1>< <%= @school.city %> ></h1><br />
      <p><em>/ <%= @school.name %> </em></p>
    </div>

    <div class="header">
      <a href="/schools"> HOME</a>
      <a href=<%= maestros_path %>> MAESTRO LOG-IN</a>
      <div class="administrative maestro button"><%= link_to "EDIT", edit_school_path %></div>
      <div class="administrative maestro button"><%= link_to "LOG-OUT", edit_school_path %></div>

    </div>

    <div class="photos">
      <div class="wrap" style="background-image:url(<%= @school.img3 %>)"></div>
      <div class="wrap two" style="background-image:url(<%= @school.img4 %>)"></div>
      <div class="wrap" style="background-image:url(<%= @school.img5 %>)"></div>
    </div>

    <div class="left">
      <h2>
        < <%= @school.name.upcase %>! >
      </h2>

      <%= @school.city %> <br />
       <em><%= @school.address %></em> <br />
    </div>

    <div class="right">
      <%= @school.summary %> <br />
      <a href="#computer"><div class="box"><b>LEARN MORE</b></div></a>  <br />
    </div>


<!-- THIS IS WHERE THE COURSE SECTION STARTS -->

    <div class="courses">
      <div class="header"></div>
    </div>
  </div>

  <div class="courses">
      <div class="left text_left">
        Administrative Fee: $<%= @school.admin_fee %> </br>
        Max Students / Class: <%= @school.max_students_per_class %>
        <h3><em>Specialized Courses:</em></h3>
        <ul>
     <!--      <li> CHILDREN </li>
          <li> PROFESSIONALS </li> -->
          <li>
            <em>Coming Soon!!</em>
          </li>
        </ul>
      </div>


       <h2>< THE COURSES ></h2>
      <table>
          <tr>
            <th># of Folks -</td>
            <th> Name -</th>
            <th> Hours/Week -</td>
            <th> Price USD -</td>
            <th> Homestay</td>
          </tr>
          <tr>
            <td><em>Private</em></td>
            <td>Lesson</td>
            <td>/hr</td>
            <td>$<%= @school.per_hr_private %></td>
            <td>none</td>
            <td class="no_border"> =>   variable/week </td>
          </tr>
              <% @school.courses.each do |course| %>
              <tr>
                <td><em>Group</em></td>
                <td><%= course.name %></td>
                <td><%= course.hrs_per_wk %></td>
                <td>$<%= course.price %></td><br>
              <td><%= @school.homestay_price%></td>
              <td class="no_border"> =>   <%= course.price + @school.homestay_price rescue 999 %></td>
              <td class="no_border">
            </tr>
          <% end %>
        </table>
       <div class="administrative maestro button"><%= link_to "New Course", edit_school_path %></div>
      </div>
      <br>
    <hr>




<!-- THIS IS THE WEBSITE IN PAGE VIEW -->

  <div class="website">

    <div class="mother_web">
      <object data=<%= @school.website %> width="55%" height="48%">
        <embed src=<%= @school.website %> width="55%" height="48%">
        </embed>
      Error: Embedded data could not be displayed.
      </object>
    </div>

    <img id="computer" class="computer" src="https://mail.google.com/mail/u/0/?ui=2&ik=a406f72f4c&view=fimg&th=1460c77bdc5320db&attid=0.4&disp=inline&realattid=f_hvbj8v443&safe=1&attbid=ANGjdJ_flC1x_mxIzn7REH-z8PcIXiacgXhpMH3Mfw4lgDlRwxVKHtJILy6l3oI-zSmyPRxLLoeiA2Hx_K0LyOf79RZOebZalCZQhDtOOJ1xQOBvkqOh0hPO6G5wnFU&ats=1400369391936&rm=1460c77bdc5320db&zw&sz=w582-h422">
  </div>



<a href="/schools">HOME</a>


<!-- THIS IS THE COMMENT SECTION -->


  <div="new_comment">
    <div class="header">
    </div>

    <div class="wrapA">
      <img class="flickr_photo" src="<%= @photo_url2 %>" alt="">
    </div>

    <div class="city" >
      <h1>< COMMENTS for <%= @school.name %> ></h1><br />
      <p><em> /comment-count: <b> <%= @school.comments.count %></b></em></p>
    </div>

    <div class="header">
      <a href="/schools"> HOME</a>
    </div>


    <div>
      <h2>< NEW COMMENT ></h2>

      <%= form_for @comment, url: school_comments_path({school_id: @school.id}) do |cf| %>
          <%= cf.label :user_name%>
          <%= cf.text_field :user_name%>
          <%= cf.label :email%>
          <%= cf.text_field :email%>
          <%= cf.label :source%>
          <%= cf.text_field :source%><br /><br />
          <%= cf.label :message%>
          <%= cf.text_area :message%><br />
          <%= cf.label :rating_overall, :placeholder => "Rate" %>
          <%= cf.text_field  :rating_overall, :placeholder => "1(miserable) - 5(magnificent!!)" %><br />

          <%= cf.submit %>
      <% end %>
    </div>

    <hr>

    <div class="list">

      <% @school.comments.each do |comment| %>

          <div><i class="fa fa-child fa-3x"></i></div><br />
          <div class="rw-ui-container <%= comment.id %>"></div>
          <div class="a_comment">
            <em>Name: </em><%= comment.user_name %> ◉ <%= comment.created_at %><br />
            <em>Source: <a href="<%= comment.source %>"><%= comment .source %></a></em> <br />
            <%= comment.message %><br />
            <form action="/schools/<%= comment.school.id if comment.school %>/comments/<%= comment.id %>" method="post">
              <%= token_tag %>
              <input type="hidden" name="_method" value="delete">
              <button type="submit">DEL</button>
            </form>

        <br /><br />
        <hr>
      </div>
    <% end %>
  </div>



<div class="bottom"></div>

</div>
















<!-- THIS IS THE STARS -->
<%= render 'rating_widget' %>

<!-- THIS IS THE THUMBS FOR COMMENTS -->

<script type="text/javascript">(function(d, t, e, m){
    // Async Rating-Widget initialization.
    window.RW_Async_Init = function(){
        RW.init({
            huid: "173546",
            uid: "726ef8fd3e8ae6ef5e42470289677e07",
            source: "website",
            options: {
                "size": "medium",
                "type": "nero",
                "style": "thumbs"
            }
        });
        RW.render();
    };




    // Append Rating-Widget JavaScript library.
    var rw, s = d.getElementsByTagName(e)[0], id = "rw-js",
        l = d.location, ck = "Y" + t.getFullYear() +
        "M" + t.getMonth() + "D" + t.getDate(), p = l.protocol,
        f = (-1 < l.search.indexOf("DBG=") ? "" : ".min"),
        a = ("https:" == p ? "secure." + m + "js/" : "js." + m);
    if (d.getElementById(id)) return;
    rw = d.createElement(e);
    rw.id = id; rw.async = true; rw.type = "text/javascript";
    rw.src = p + "//" + a + "external" + f + ".js?ck=" + ck;
    s.parentNode.insertBefore(rw, s);
}(document, new Date(), "script", "rating-widget.com/"));</script>