config/routes.rb
Rails.application.routes.draw do

  root 'schools#root'
  get 'faq' => 'administrators#faq'
  get 'links' => 'administrators#links'
  get 'contact' => 'administrators#contact'

  get 'schools/search' => 'schools#search'

  resources :schools do
    resources :courses
    resources :comments, only: [:create, :destroy]
    resources :homestays
  end

  resources :maestros do
  end

  resources :administrators do
  end

  get 'sessions/new' => 'sessions#new', as: 'log-in'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy', as: 'log-out'

end

app/models/maestro.rb
class Maestro < ActiveRecord::Base
  has_secure_password
end

app/controllers/maestros_controller.rb
class MaestrosController < ApplicationController

  def index
    @maestro = current_maestro
    @maestros = Maestro.all
  end

  def new
    @maestro = Maestro.new
  end

  def create
    Maestro.create(maestro_params)
    redirect_to maestros_path
  end

  def show
    @maestro = Maestro.find(params[:id])
  end

  def edit
    @maestro = Maestro.find(params[:id])
  end

  def update
    edited_maestro = Maestro.find(params[:id])
    edited_maestro.update(maestro_params)
    redirect_to maestro_path
  end

  private

  def maestro_params
    params.require(:maestro).permit(:email, :phone_number, :history, :teaching_methodology, :other, :profile_pic, :school_id, :password, :password_confirmation)
  end
end

app/views/maestros/_form.html.erb
<%= form_for @maestro do |f| %>
    <h4>PROVIDE CONTACT INFORMATION:</h4>
      Email:  <%= f.text_field :email %>  <br />
      Phone-Number: <%= f.text_field :phone_number %>   <br />
      School ID: <%= f.text_field :school_id %>  <br />

    <h4>FILL OUT YOUR PROFILE:</h4>
      Profile Picture URL: <%= f.text_field :profile_pic %>   <br />
      History: <%= f.text_area :history %>  <br />
      Teaching Methodology: <%= f.text_area :teaching_methodology %>  <br />
      Other Infomration: <%= f.text_area :other %>  <br />

    <h4>SET YOUR PASSWORD:</h4>
      Password: <%= f.password_field :password %>  <br />
      Confirm your Password: <%= f.password_field :password_confirmation %>  <br />

  <br />
  <%= f.submit %>

<% end %>

app/views/maestros/_logged_in.html.erb
<h1>You are logged in!</h1>

<h2>What do you want to do now?</h2>

<ul>
  <li>
    Edit your profile.
      <%= link_to "Maestro Profile", maestro_path(current_maestro) %>
  </li>
  <li>
    Edit school information.
      <%= link_to "Maestro School", school_path(current_maestro.school_id)%>
  </li>
    <li>
    Browse all schools.
      <%= link_to "All Schools", schools_path %>
  </li>
</ul>

app/views/maestros/edit.html.erb
<h1>CREATE A NEW 'MAESTRO' ACCOUNT:</h1>

  <%= render form %>

app/views/maestros/index.html.erb
<h2>Welcome</h2>

<% if current_maestro %>
  <p>
    <%= current_maestro.email %> ... is logged in
  </p>
  <%= link_to "Log-Out", log_out_path, method: :delete %>
  <%= render "logged_in" %>
<% else %>
  <%= link_to "Log-In", log_in_path %>
  <%= link_to "Sign-Up", "/maestros/new" %>
<% end %>

<h1>List of all 'Maestros'</h1>

<ul>
  <% @maestros.each do |maestro| %>
    <li>
      <%= maestro.email %>
    </li>
  <% end %>
</ul>

app/views/maestros/new.html.erb
<h1>Create a new 'Maestro'</h1>

<%= render 'form' %>

app/views/maestros/show.html.erb
<%= link_to "Edit Profile", edit_maestro_path %>
<%= link_to "All Maestros", maestros_path %>

<br />
<%= @maestro.email %><br />
<%= @maestro.phone_number %><br />
<%= @maestro.history %><br />
<%= @maestro.teaching_methodology %><br />
<%= @maestro.other %><br />
<img src="<%= @maestro.profile_pic %>"><br />
<%= @maestro.school_id %><br />


<%= render 'logged_in' %>